### ISSUE TITLE
pythin examples fail

### ISSUE THREAD

**Issue by yurivict** [wjakob/nanogui#298]
python2.7 fails this way:
```
$ python2 example1.py
Traceback (most recent call last):
  File "example1.py", line 12, in <module>
    import nanogui
ImportError: /usr/local/lib/python2.7/site-packages/nanogui.so: Undefined symbol "PyInstanceMethod_Type"
```

python3.4 fails this way:
```
$ python3.4 example1.py 
Traceback (most recent call last):
  File "example1.py", line 12, in <module>
    import nanogui
ImportError: /usr/local/lib/python3.4/site-packages/nanogui.so: Undefined symbol "PyMem_Calloc"
```

**Comment by svenevs** [comment]
When building locally, the build structure looks like this:

```
build/
    libnanogui.so  # the C++ library
    example1 # c++ example 1
    python/
        # LIBRARY FILE HERE FOR PYTHON
```

The `build/python` folder is where you would need to run the example executables from

```console
$ cd build/python

# python or python3 depending on what you built
$ python ../../python/example1.py
```

When a user installs nanogui (which you seem to be pursuing), they must make sure to [set `PYTHONPATH` accordingly](https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH).  This is what tells python "hey, in addition to `site-packages`, look here".  `site-packages` is where things installed with e.g. `pip` typically get put, unless specifically overriden.

On this note, this repository is going to remain open for the foreseeable future, but will eventually turn into "bugfixes only".  The future version of NanoGUI [is here](https://github.com/mitsuba-renderer/nanogui), which has a proper `setup.py` for python installation convenience.

I'm going to say this here, but it relates to some of the other issues you have raised: NanoGUI is not designed to be installed, it is designed to build on its own as a git submodule.  This guarantees that your open source project can build its GUI library (NanoGUI) without needing the user to first compile and install it.  So there's no real notion of first install NanoGUI, then `find_package(nanogui)`.  Fixes to the installation setup are certainly welcome, but I don't think the existing installation stuff received *too* much attention given the design for submodules.  Where python is concerned, though, having it installed is really the only way if you want to `import nanogui` from a script anywhere on the system.
